const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const rendererRoot = path.join(__dirname, '..', 'src', 'renderer');
const mainSource = fs.readFileSync(path.join(__dirname, '..', 'src', 'main', 'main.js'), 'utf8');
const preloadSource = fs.readFileSync(path.join(__dirname, '..', 'src', 'main', 'browser-shell-preload.js'), 'utf8');

test('browser shell exposes a multi-tab strip and icon-only toolbar actions', () => {
  const html = fs.readFileSync(path.join(rendererRoot, 'browser-shell.html'), 'utf8');
  const script = fs.readFileSync(path.join(rendererRoot, 'browser-shell.js'), 'utf8');
  const css = fs.readFileSync(path.join(rendererRoot, 'browser-shell.css'), 'utf8');
  assert.match(html, /id="tabs"/);
  assert.match(html, /id="tab-menu"[^>]*aria-controls="tab-switcher-panel"/);
  assert.match(html, /id="tab-switcher-panel"[^>]*role="dialog"/);
  assert.match(html, /id="tab-switcher-search"/);
  assert.match(html, /id="tab-switcher-open"/);
  assert.match(html, /id="tab-switcher-closed"/);
  assert.match(html, /id="new-tab"/);
  assert.match(html, /id="browser-settings-toggle"/);
  assert.match(html, /id="browser-settings-panel"/);
  assert.match(html, /id="setting-agent-api-url"/);
  assert.match(html, /id="setting-search-engine-url"/);
  assert.match(html, /id="setting-shortcut-reload"/);
  assert.match(html, /id="setting-shortcut-devtools"/);
  assert.match(html, /id="setting-gesture-sequence"/);
  assert.match(html, /id="browser-settings-ai"/);
  assert.match(html, /id="connection-country"/);
  assert.match(html, /id="connection-ip"/);
  assert.match(html, /id="connection-latency"/);
  assert.doesNotMatch(html, /class="identity-dot"/);
  assert.doesNotMatch(html, /class="shell-status-dot"/);
  assert.doesNotMatch(html, /id="connection-label"/);
  assert.doesNotMatch(script, /connection-label/);
  assert.match(html, /shell-icon-open/);
  assert.match(script, /function createTab\(/);
  assert.match(script, /createTab\(startUrl\);/);
  assert.match(script, /function closeTab\(/);
  assert.match(script, /function beginTabDrag\(/);
  assert.match(script, /function updateTabDrag\(/);
  assert.match(script, /function finishTabDrag\(/);
  assert.match(script, /function renderTabSwitcher\(/);
  assert.match(script, /function rememberClosedTab\(/);
  assert.match(script, /recentlyClosedTabs\.length = Math\.min\(recentlyClosedTabs\.length, 20\)/);
  assert.match(script, /select\.dataset\.tabSwitcherAction = kind === 'open' \? 'switch' : 'restore'/);
  assert.match(script, /tabSwitcherPanel\?\.addEventListener\('click'/);
  assert.match(script, /toggleTabSwitcher\(\);/);
  assert.match(script, /\(event\.ctrlKey \|\| event\.metaKey\) && event\.shiftKey && event\.key\.toLowerCase\(\) === 'a'/);
  assert.match(script, /tabItems\.splice\(state\.targetIndex, 0, moved\)/);
  assert.match(script, /window\.addEventListener\('pointermove', updateTabDrag/);
  assert.match(script, /window\.addEventListener\('pointercancel', \(\) => finishTabDrag\(true\)\)/);
  assert.match(script, /event\.key === 'Escape'[\s\S]*?finishTabDrag\(true\)/);
  assert.match(script, /DEFAULT_SEARCH_ENGINE_URL/);
  assert.ok(script.includes('chrome://'));
  assert.ok(script.includes('此浏览器不支持 chrome:// 内部页面'));
  assert.match(script, /function renderHistoryPage\(/);
  assert.match(script, /function openHistoryPage\(/);
  assert.match(script, /case 'history': openHistoryPage\(\)/);
  assert.match(script, /case 'passwords': await window\.shellApi\?\.openExtensionManager\?\.\('passwords'\)/);
  assert.match(preloadSource, /openExtensionManager: \(view\) => ipcRenderer\.invoke\('browser-shell:open-manager', view\)/);
  assert.match(mainSource, /shellHandle\('browser-shell:open-manager', \(_event, view\)/);
  assert.match(mainSource, /const targetView = view === 'passwords' \? 'passwords' : 'extensions'/);
  assert.match(script, /case 'bookmarks': \{[\s\S]*?showBookmarkMenu\(\{ type: 'root' \}/);
  assert.match(script, /case 'new-window': setShellStatus\('当前版本暂不支持独立浏览器窗口'/);
  assert.match(script, /case 'incognito': setShellStatus\('当前版本暂不支持无痕窗口'/);
  assert.match(script, /清空历史记录/);
  assert.match(css, /\.history-view\s*\{/);
  assert.match(script, /value === 'about:blank' \? ''/);
  assert.match(script, /function saveBrowserSettings\(/);
  assert.match(script, /Control|ctrlKey/);
  assert.match(css, /\.browser-tab\.is-active/);
  assert.match(css, /\.browser-tab\.is-dragging/);
  assert.match(css, /\.browser-tab\.tab-reorder-shift/);
  assert.match(css, /\.browser-tab-close\s*\{[^}]*opacity:\s*0[^}]*pointer-events:\s*none/s);
  assert.match(css, /\.browser-tab:hover \.browser-tab-close, \.browser-tab:focus-visible \.browser-tab-close/);
  assert.match(css, /\.tab-active-surface\s*\{[^}]*transition:[^}]*transform/s);
  assert.match(css, /background-image:\s*linear-gradient\(rgba\(15, 20, 35, calc\(1 - var\(--shell-image-opacity\)\)\), transparent\), var\(--shell-image\), radial-gradient/);
  assert.match(css, /\.tab-switcher-panel\s*\{/);
  assert.match(css, /\.tabs\s*\{[^}]*flex:\s*0 1 auto/s);
  assert.match(css, /\.tabs\s*\{[^}]*overflow-x:\s*auto/s);
  assert.match(css, /\.browser-tab\s*\{[^}]*min-width:\s*88px/s);
  assert.doesNotMatch(script, /applyTabDensity|is-compact|TAB_COMPACT_WIDTH/);
  assert.doesNotMatch(css, /browser-tab\.is-compact/);
  assert.match(css, /\.browser-settings-panel/);
  assert.match(css, /\.go-button\s*\{[^}]*width:\s*34px/s);
  assert.match(html, /id="bookmark-toggle"/);
  assert.match(html, /<form id="address-form"[\s\S]*?<button id="bookmark-toggle"[\s\S]*?bookmark-star[\s\S]*?>☆<\/span>[\s\S]*?<\/form>/);
  assert.match(html, /<\/form>\s*<button id="agent-toggle" class="icon-button toolbar-agent-button"/);
  assert.doesNotMatch(html, /bookmark-beads/);
  assert.match(html, /id="bookmark-bar"/);
  assert.match(html, /id="extension-toolbar"/);
  assert.match(html, /id="extensions-close"/);
  assert.match(html, /id="open-extension-manager"/);
  assert.match(script, /candidate\.enabled && candidate\.pinned/);
  assert.match(script, /data-extension-details/);
  assert.match(script, /data-extension-pin/);
  assert.match(script, /setExtensionPinned/);
  assert.match(preloadSource, /setExtensionPinned:.*browser-shell:set-extension-pinned/);
  assert.match(mainSource, /browser-shell:set-extension-pinned/);
  assert.match(html, /id="setting-new-tab-banner-source"/);
  assert.match(html, /id="new-tab-sites-editor"/);
  assert.match(html, /id="address-suggestions"/);
  assert.match(script, /function renderAddressSuggestions\(/);
  assert.match(script, /function toggleBookmark\(/);
  assert.match(script, /bookmarkStar\.textContent = saved \? '⭐' : '☆'/);
  assert.match(script, /function toggleActiveDevTools\(/);
  assert.match(script, /function renderNewTabPage\(/);
  assert.match(script, /function saveNewTabBackgroundSettings\(/);
  assert.match(script, /newTabAppearance/);
  assert.match(script, /newTabBackgroundOpacity/);
  assert.match(script, /newTabBackgroundBlur/);
  assert.match(script, /content\.append\(searchForm, sites\)/);
  assert.match(script, /function setNewTabZoomFactor\(/);
  assert.match(script, /if \(item\?\.isNewTab\) \{[\s\S]*?setNewTabZoomFactor\(item\.newTabView/);
  assert.match(script, /function newTabSitesForRender\(/);
  assert.match(script, /for \(const site of recognizedNewTabSites\)/);
  assert.match(script, /void recordCommonSiteVisit\(item\.url\)/);
  assert.match(preloadSource, /getCommonSites:.*browser-shell:get-common-sites/);
  assert.match(preloadSource, /recordCommonSiteVisit:.*browser-shell:record-common-site-visit/);
  assert.match(mainSource, /browser-shell:get-common-sites/);
  assert.match(mainSource, /browser-shell:record-common-site-visit/);
  assert.match(script, /bindTabEvents\(item\);\s*if \(item\.url && !isNewTabUrl\(item\.url\)\) item\.view\.setAttribute\('src', item\.url\)/);
  assert.match(script, /const hadView = Boolean\(item\.view && !item\.isNewTab\);[\s\S]*?if \(hadView\) await targetView\.loadURL\(url\)/);
  assert.match(script, /await agentNavigate\(\{ tabId: activeTabId, url \}\)/);
  assert.match(script, /function toggleBookmarkBar\(/);
  assert.match(script, /onOpenNewTab/);
  assert.match(script, /createTab\(url \|\| 'about:newtab'\)/);
  assert.match(script, /ctrlKey && event\.altKey/);
  assert.match(mainSource, /input\.control \|\| input\.meta/);
  assert.match(mainSource, /key === 't'/);
  assert.match(script, /content\.append\(mediaWrap\)/);
  assert.match(script, /PAGE_LOAD_TIMEOUT_MS\s*=\s*20000/);
  assert.match(script, /did-frame-finish-load/);
  assert.match(script, /加载超时：代理或目标站点无响应/);
  assert.match(script, /render-process-gone/);
  assert.match(script, /browser_configure_shortcuts/);
  assert.match(css, /\.address-suggestions/);
  assert.match(css, /\.bookmark-bar/);
  assert.match(css, /\.bookmark-bar\s*\{[^}]*overflow:\s*hidden[^}]*scrollbar-width:\s*none/s);
  assert.match(css, /\.bookmark-bar::\-webkit-scrollbar\s*\{[^}]*display:\s*none/s);
  assert.match(css, /--shell-new-tab-opacity/);
  assert.match(css, /--shell-new-tab-blur/);
  assert.match(css, /\.new-tab-display-settings/);
  assert.match(css, /\.new-tab-display-field input\[type="range"\]/);
  assert.match(css, /\.new-tab-view\[data-display-mode="immersive"\] \.new-tab-media-scrim\s*\{[^}]*var\(--shell-bg\)/s);
  assert.match(css, /\.new-tab-search\s*\{[^}]*background:\s*color-mix/s);
  assert.match(css, /\.browser-tab\.is-active, \.browser-tab\.is-active:hover\s*\{[^}]*color:\s*var\(--tab-text/s);
  assert.match(css, /\.tab-active-surface\s*\{[^}]*background:\s*var\(--tab-page-color,/s);
  assert.match(mainSource, /newTabBackgroundOpacity/);
  assert.match(mainSource, /newTabBackgroundBlur/);
  assert.match(css, /\.toolbar-agent-button\s*\{[^}]*flex:\s*0 0 34px/s);
  assert.match(css, /\.bookmark-button\s*\{[^}]*right:\s*4px/s);
  assert.doesNotMatch(css, /#address:focus\s*\{[^}]*padding-right:\s*78px|#address:focus\s*~\s*\.address-agent-button|\.address-input-wrap:focus-within \.bookmark-button/);
  assert.doesNotMatch(script, /bookmarkToggle\?\.addEventListener\('mousedown'/);
  assert.match(script, /agentToggle\?\.addEventListener\('click', \(event\) => \{[\s\S]*?setAgentOpen\(!open\)/);
  assert.match(css, /\.new-tab-view/);
  assert.ok(html.indexOf('class="navigation"') < html.indexOf('class="identity"'));
});

test('native menu is hidden and sensitive data is confirmed before persistence', () => {
  assert.match(mainSource, /Menu\.setApplicationMenu\(null\)/);
  assert.match(mainSource, /async function confirmSecretRetention\(/);
  assert.match(mainSource, /requestUiConfirmation\(sender/);
  assert.match(mainSource, /app:confirmation-request/);
  assert.match(mainSource, /retainSecrets: retention\.retain/);
  assert.match(mainSource, /urlContainsSecret\(/);
  assert.match(mainSource, /function publicSettings\(/);
  assert.match(mainSource, /browser-shell:get-settings/);
  assert.match(mainSource, /browser-shell:get-bookmarks/);
  assert.match(mainSource, /before-input-event/);
  assert.match(mainSource, /input-event/);
  assert.match(mainSource, /handleGuestInput/);
  assert.match(mainSource, /DEFAULT_MOUSE_GESTURE/);
  assert.match(mainSource, /browser:install/);
  assert.match(mainSource, /async function confirmAgentKeyRetention\(/);
  assert.match(mainSource, /lookupNodeCountry\(/);
  assert.match(mainSource, /did-finish-load'[\s\S]*?sendBrowserConnectionDetails\(profile\.id\)/);
  assert.doesNotMatch(mainSource, /settings:\s*\{\s*\.\.\.state\.settings\s*\}/);
});

test('browser shell places its tabs in the native title-bar overlay', () => {
  assert.match(mainSource, /titleBarStyle:\s*'hidden'/);
  assert.match(mainSource, /titleBarOverlay:\s*\{/);
  assert.match(mainSource, /height:\s*42/);
  const css = fs.readFileSync(path.join(rendererRoot, 'browser-shell.css'), 'utf8');
  assert.match(css, /-webkit-app-region:\s*drag/);
  assert.match(css, /titlebar-area-width/);
});
